import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";

import {
  ClerkProvider,ClerkLoading
} from '@clerk/nextjs'
import { AnimatedLoader } from "./components/animated-loader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        {children}
        <ClerkLoading>
            {/* Render a loading spinner or message */}
            <div><AnimatedLoader/></div>
          </ClerkLoading>
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
